# Start from your WRF runtime container
# There are several errors using this iwrf container
# and I do not have time to deal with it right now
# FROM ncar/iwrf:20241203
FROM kkeene44/wrf-coop:version16

# Install Python 3 and pip
RUN dnf -y update && \
    dnf -y install python3 && \
    ln -s /usr/bin/python3 /usr/bin/python

# Upgrade pip
RUN python -m pip install --upgrade pip

# Install Python packages
RUN pip install \
    omegaconf \
    jinja2 \
    requests \
    pandas

# (Optional) Set the working directory to wrfuser home
# WORKDIR /home/wrfuser
